#!/usr/bin/perl

#Name:          logInterrogate.pl
#Purpose:       Find who fell first and hardest for a given error type in a list                                                                             of given ADS
#Author:        Sam Grayston
#Date:          20/03/2013


use strict;
use warnings;

main();


sub main{
#Open a list of errors to find and initialise to array;
open (ERRORS, "./errors.txt") or die "Cannot open errors.txt";
my @errors  = <ERRORS>;
chomp @errors;
my $regex = join ('|',@errors);
print $regex;
close ERRORS;

#Open a list of ADS to find the error for to array
open (COMP, "./components.txt") or die "Cannot open components.txt" ;
my @comp  = <COMP>;
close COMP;

#Make a temp directory for the files generated by the host

mkdir "./Interrogation.$$";

foreach my $ads (@comp){
chomp ($ads);
my $cmd = "ssh cjcadmin\@$ads /bin/grep -A 1 \'$ARGV[0].*2013\' /reuters/logs/ads/ads.log*| grep -B 1 -P  '$regex'";
$cmd = "ssh cjcadmin\@$ads /bin/grep -A 1 \'$ARGV[0].*2013\' /reuters/logs/adh/adh.log*| grep -B 1 -P  '$regex'" if $ads =~ /^.*(d|m)0[0-9][0-9](a|b)$/;
my @expect = runExpectCommand ($cmd,"D\@rk0ne");
foreach (@expect){
print "\n$ads" if $_ =~ /Permission/;
}
@expect = grep (!/--/, @expect);
foreach (@expect){
$_ =~ s/\r//;
chomp $_  if $_ =~ />\n$/
}
open (TEMP, ">./temporary");
print TEMP @expect;
close TEMP;
open (TEMP, "./temporary");
open (FILE, ">./Interrogation.$$/$ads.$$");
my @temp = <TEMP>;
@temp = grep (/$regex/, @temp);
@temp = grep (!/grep/, @temp);
foreach (@temp){
$_ =~ s/^.*:(.*:\d+:\d+\s\d+>.*)/$1/g;

print FILE $_ if $_ =~ /^.*($ARGV[0])\s+(07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22):/;
}
close TEMP;
close FILE;
}
(my $date = $ARGV[0]) =~ s/\s//;
open (DSUM, ">./dailySum.$date");
my @files = glob ("Interrogation.$$/*");
print DSUM "My Errors listed = $regex\n";

foreach (@files){
my $count = `wc -l $_`;
print DSUM "$_, $count";
}
}


sub runExpectCommand {

   my($command,$password) = @_;
   my ($expectFile) = "./sshlogin.exp";
   # We need to modify the password to send if it contains metacharacters
   $password=~s/\$/\\\$/g;
   $password=~s/\@/\\\@/g;
   $password=~s/\*/\\\*/g;
   $password=~s/\&/\\\&/g;

   open(EXPECTFILE,"> $expectFile");
   print EXPECTFILE ("#!/usr/bin/expect -f\n");
   print EXPECTFILE ("spawn $command\n");
   print EXPECTFILE ("match_max 100000\n");
   print EXPECTFILE ("expect -- \"*?assword: \"\n");
   print EXPECTFILE ("send -- \"$password\\r\"\n");
   print EXPECTFILE ("expect -- \"\\r*\"\n");
   print EXPECTFILE ("send -- \"exit\\r\"\n");
   print EXPECTFILE ("expect eof\n");
   close (EXPECTFILE);
   system("chmod +x $expectFile");
   #system("$expectFile");
   my @expect = (`$expectFile`);
   system("rm $expectFile");
   return (@expect);
}

